apiVersion: v2
name: novu
description: Helm chart to deploy Novu, the open-source notification infrastructure
type: application
version: 0.2.1
# renovate: image=ghcr.io/novuhq/novu/web
# renovate: image=ghcr.io/novuhq/novu/ws
# renovate: image=ghcr.io/novuhq/novu/api
# renovate: image=ghcr.io/novuhq/novu/worker
appVersion: "2.1.0"
home: https://github.com/nova-edge/novu-chart
icon: https://raw.githubusercontent.com/novuhq/novu/next/apps/web/public/static/images/novu.png
sources:
  - https://github.com/nova-edge/novu-chart
keywords:
  - novu
  - notifications
  - notification-center
  - sms
  - email
  - push
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/category: integration-delivery
maintainers:
  - name: Ugo Mignon
    email: ugo.mignon@gameverse.app
  - name: Jordan Labrosse
    email: jordan.labrosse@gameverse.app
dependencies:
  - name: redis
    version: 20.13.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: mongodb
    version: 16.5.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
