apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "novu.fullname" . }}-config
  labels:
    app: {{ include "novu.name" . }}
    component: config
data:
  NODE_ENV: {{ .Values.global.env.nodeEnv | quote }}
  MONGO_URL: "mongodb://{{ include "mongodb.fullname" . }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.mongodb.service.ports.mongodb }}/novu"
  MONGO_MAX_POOL_SIZE: {{ .Values.global.env.mongodb.maxPoolSize | quote }}
  REDIS_HOST: "{{ include "redis.fullname" . }}-master.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_PORT: {{ .Values.redis.master.service.ports.redis | quote }}
  REDIS_CACHE_SERVICE_HOST: "{{ include "redis.fullname" . }}-master"
  REDIS_CACHE_SERVICE_PORT: {{ .Values.redis.master.service.ports.redis | quote }}
  S3_LOCAL_STACK: {{ .Values.global.env.s3.localStack | quote }}
  S3_BUCKET_NAME: {{ .Values.global.env.s3.bucketName | quote }}
  S3_REGION: {{ .Values.global.env.s3.region | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.env.aws.accessKeyId | quote }}
  NEW_RELIC_APP_NAME: {{ .Values.global.env.newRelic.appName | quote }}
  API_ROOT_URL: {{ .Values.global.env.apiRootUrl | quote }}
  API_PORT: {{ .Values.api.port | quote }}
  API_CONTEXT_PATH: {{ .Values.api.contextPath | quote }}
  REACT_APP_API_URL: "http://{{ include "novu.api.fullname" . }}:{{ .Values.api.port }}"
  REACT_APP_ENVIRONMENT: {{ .Values.global.env.nodeEnv | quote }}
  REDIS_DB_INDEX: "2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "novu.fullname" . }}-web-env-config
  labels:
    app: {{ include "novu.name" . }}
    component: config
data:
  env-config.js: |
    window._env_ = {
        REACT_APP_API_URL: "${REACT_APP_API_URL}",
        NODE_ENV: "${NODE_ENV}",
        REACT_APP_WIDGET_EMBED_PATH: "${REACT_APP_WIDGET_EMBED_PATH}",
        REACT_APP_IS_SELF_HOSTED: "${REACT_APP_IS_SELF_HOSTED}",
        REACT_APP_WS_URL: "${REACT_APP_WS_URL}"
    };